config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books do
    resources :reviews
  end
  root 'books#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    belongs_to :category
    has_many :reviews

    has_attached_file :book_img, styles: { :book_index => "250x350>", :book_show => "325x475>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :book_img, content_type: /\Aimage\/.*\z/ #allow us to view images
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :books
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :book
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :find_book, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, only: [:new, :edit]
    def index
        if params[:category].blank? #if the category params are blank and we didnt pass any we want to display all the books because we are not filtering
            @books = Book.all.order("created_at DESC") #display all books from the model
        else
           @category_id = Category.find_by(name: params[:category]).id # getting id of category that were passing in 
           @books = Book.where(:category_id => @category_id).order("created_at DESC") # getting books where category id is books category id 
        end
    end

    def show
        if @book.reviews.blank?
          @average_review = 0
          #if book has no reviews setting to 0
        else
            @average_review = @book.reviews.average(:rating).round(2)
            #if reviews are not blank and average them on rating attribute
        end
    end

    def new
        @book = current_user.books.build
        # line 13 explained: when we create select_tag for the dropdown menu in the form partial file,
        # options_for_select requires an arrays, which provide the text for the dropdown option (its name) 
        # and the value it represents (its id attribute)
        @categories = Category.all.map{ |c| [c.name, c.id] } # Way to access categories when we create a new book
    end

    def create
        @book = current_user.books.build(book_params)
        @book.category_id = params[:category_id] # Associate a book with a category id

        if @book.save # If book saves redirect to root path 
            redirect_to root_path
        else 
            render 'new'
        end
    end

    def edit 
        @categories = Category.all.map{ |c| [c.name, c.id] }
    end

    def update
        @book.category_id = params[:category_id]
        # Checking if book is updated successfully 
        if @book.update(book_params)
            redirect_to book_path(@book)
        else 
            render 'edit'
        end
    end

    def destroy 
        @book.destroy 
        redirect_to root_path
    end


    private 

        def book_params
            params.require(:book).permit(:title, :description, :author, :category_id, :book_img)
        end

        def find_book
            @book = Book.find(params[:id])
        end

end

# @ instances variables are what we use in our views/html template 

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :find_book
    before_action :find_review, only: [:edit, :update, :destroy]
    before_action :authenticate_user!, only: [:new, :edit]

    def new
        @review = Review.new 
    end

    def create 
        @review = Review.new(review_params)
        @review.book_id = @book.id #sets review attribute to the current book.id
        @review.user_id = current_user.id
         #line 10-11  - associate a review with the current book and with the current user
         #instance variables/attributes available because created those migrations  
        if @review.save
            redirect_to book_path(@book)
        else 
          render 'new'
        end
    end

    def edit 
      #@review = Review.find(params[:id])
      #we are finding book so the @review instance is avialable 
    end

    def update
      #@review = Review.find(params[:id])
      if @review.update(review_params) #when a user fills out the form there passing in review params from the private method review params
        redirect_to book_path(@book)
        #line 29 at @book is avialable because we are finding the book
      else
        render 'edit'
      end
    end

    def destroy 
      @review.destroy
      redirect_to book_path(@book)
    end

    private
      def review_params
        params.require(:review).permit(:rating, :comment)
      end 

      def find_book
        @book = Book.find(params[:book_id])
        #specify :book_id instead of just :id because we are in the reviews controller
        #and a review is associated with a book_id 
      end 

      def find_review
        @review = Review.find(params[:id])
        # line 47 refactored from line 27 in a private method so we can call it from the edit, update and destroy methods.

end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book, :html => {:multipart => true } do |f| %>
    <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a Category" ) %>
    <%= f.file_field :book_img %>
    <%= f.input  :title, label: "Book Title" %>
    <%= f.input  :description %>
    <%= f.input  :author %>
    <%= f.button :submit, :class => 'btn-custom2'  %>
<% end %>

<!--Creating a form for new users to create a book!-->

app/views/books/edit.html.erb
<div class="col-md-6 col-md-offset-3">

    <div class="edit-book-form">
        <h1>Edit Book</h1>

        <%= simple_form_for @book, :html => {:multipart => true } do |f| %>
            <%= f.select :category_id, @categories %>
            <%= f.file_field :book_img %>
            <%= f.input  :title, label: "Book Title" %>
            <%= f.input  :description %>
            <%= f.input  :author %>
            <%= f.button :submit, :class => "btn-custom2"%>
        <% end %>
    </div>
</div>

app/views/books/index.html.erb
<!-- <h1>Index Views</h1> !--> 
<!-- Looping through books to display them !--> 
<h1 class= "current-category"><%= params[:category] %> </h1> <!-- params is the category name !-->

<% if @books.count == 0  %> <!-- books is avialable because it was defined in index method in book controller!-->

    <h1>There are no books currently in this category</h1>

<% else %>

<div class="row">

  <% @books.each do |book| %>

    <div class="col-md-3"> <!-- books wrapped inside a column !-->
      <a href="/books/<%= book.id %>"> <!-- Installing an anchor tag to take us to the show page instance of book!-->
        <%= image_tag book.book_img.url(:book_index), class: "book"  %> <!-- used to display images url book index corresponding size of book !-->
      </a>
    </div>

  <% end %>

  </div>

  
<% end %>

app/views/books/new.html.erb
<div class="col-md-6 col-md-offset-3">
    
    <div class="new-book-form">
        <h1>New Book</h1> 

        <%= render 'form' %>
    </div>
</div>






<!---renders form partial !-->

app/views/books/show.html.erb
<div class='row'>

    <div class="col-md-4">
      <%= image_tag @book.book_img.url(:book_show), class: "book-show" %>
    </div>

    <div class="col-md-8">
      <div class="book-info">
        <h2 class="book-title"><%= @book.title %> </h2>
        <h3 class="book-author"><span>From</span> <%= @book.author %> </h3>
        <h2 class="avg-rating">Average Rating</h2>
        <div class="average-review-rating" data-score=<%=@average_review%>></div>
        <span class="number-of-reviews"> Based on <%= @book.reviews.count %> reviews</span>
        <p class="book-desc"><%= @book.description %> </p>
      </div>
    </div>
</div>

<div class="row">
  <div class="col-md-4"> 
    <div class="reviews">
      <h1>Reviews</h1>
      <%= render @book.reviews %>
      <!--Rendering book reviews -->
      <!-- Has its own row and columns-->
      <!--Where the reviews/rating will go -->
      <div>
          <%= link_to "Add Review", new_book_review_path(@book), class: "btn-custom" %>
      </div>
      
     </div>

   </div>

</div>

<div class="links btn-group">

  <%= link_to "Back", root_path, class: "btn btn-custom" %>

  <% if user_signed_in? %>

    <% if @book.user_id == current_user.id %> <!--- if the books current user id is equivalent to the current user id we want links to appear!-->

        <%= link_to "Edit", edit_book_path(@book), class: "btn btn-custom"  %>
        <%= link_to "Delete", book_path(@book), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom"  %>

    <% end %>

  <% end %>
</div>
<script>
  $('.review-rating').raty({
    readonly:true,
    score:function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>

<script>
  $('.average-review-rating').raty({
    readOnly: true,
    path: '/assets/',
    score: function() {
      return $(this).attr('data-score')
    }
  });
 </script> 

 <!-- script tag helps with all the functionality that was added up top-->

<!--script tag associated with js. partial is rendered in the show page. 
targets class that we have of review rating -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookReview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
  <nav class="navbar navbar-default">

    <div class="container">

      <div class="navbar-header">
        <%= link_to "Book Review", root_path, class: "navbar-brand" %>
      </div>

      <ul class="nav navbar-nav">
        <li> <%= link_to "Sign up", new_user_registration_path %>
        <% if user_signed_in? %> <!-- Checking if user is signed in!-->
          <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </li>
        <% else %>
          <li> <%= link_to "Login", new_user_session_path %> </li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">


        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
          aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% Category.all.each do |category| %> 
              <li class= "<%= 'active' if params[:category] == category.name %>"> 
                <%= link_to category.name, books_path(category: category.name), class: "link" %>
              </li>
            <% end %>
          </ul>
        </li>



        <% if user_signed_in? %>
          <li><%= link_to "Add Book", new_book_path %> </li>
        <% end %>
      </ul>



    </div>

  </nav>

  <p class= "notice"><%= notice %> </p>
  <p class= "alert"><%= alert %> </p>

  <div class = "container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@book, @book.reviews.build]) do |f| %>
  <div id="rating-form">
    <label>Rating</label>
  </div>
  <%= f.input :comment %>
  <%= f.button :submit, :class => "btn-custom2" %>
<% end %>

<script>
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>
<!--Script tag allows us to convert the star rating into an integer value for rating, so when we are in the form partial it allows a user to click the number of stars -->


<!--passing two different parameters @book.reviews is possible from association where a book has 
many reviews. @book is getting there current instance from @book, reason why we did the find beforer action so we have access to instance variable.
.build is building reviews from that book -->

app/views/reviews/_review.html.erb
<div class="review">
  <div class="review-rating" data-score="<%= review.rating %>"></div>
  <p class="review-comment"><%= review.comment %> </p>

  <% if user_signed_in? %>

    <% if review.user_id == current_user.id %>

      <div class="links btn-group">

        <%= link_to "Edit", edit_book_review_path(review.book, review), class: "btn btn-custom" %>

        <%= link_to "Delete", book_review_path(review.book, review), method: :delete, 
          data: { confirm: "Are you sure?"}, class: "btn btn-custom" %>
      </div>
    
    <% end %>
  <% end %>
</div>


<!--Were putting the link to in the review partial file so its rendered for each instance of the view-->  

<!--Displaying/Showing all books -->

app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">
<!--Not just rendering form because in review _form partial were building reviews for the current book-->
  <div class="edit-review-form">

  <h1> Edit Form </h1>

  <%= simple_form_for([@book, @review]) do |f| %>
      <div id="rating-form">
        <label>Rating</label>
      </div>
      <%= f.input :comment  %>
      <%= f.button :submit, :class => "btn-custom2" %>
  <% end %>
  </div>
</div>

<script>
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

<%= link_to 'Back', :back %>

app/views/reviews/new.html.erb
<div class="col-md-6 col-md-offset-3">
    
    <div class="new-review-form">

        <h1> New Review </h1>

        <%= render 'form' %>
    </div>   
</div>